### ISSUE TITLE
有兴趣把这个工具做通用化，放到 YApi 官方吗？

### ISSUE THREAD

**Issue by hellosean1025** [wxynihao/yapi-code-generator#2]
你好，我是 yapi 作者，有兴趣把这个工具做通用化，放到 YApi 官方吗？

可参考该工具：https://github.com/hellosean1025/yapi-gen-js-code

**Comment by wxynihao** [comment]
> 你好，我是 yapi 作者，有兴趣把这个工具做通用化，放到 YApi 官方吗？
> 
> 可参考该工具：https://github.com/hellosean1025/yapi-gen-js-code

你好，有兴趣的，只是目前公司加班严重，时间和进度暂时没有保证，有空我就做一点，等做的差不多了我联系你

**Comment by hellosean1025** [comment]
好，感谢
